# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=100)),
                ('birthdate', models.DateField(verbose_name='Data de nascimento')),
                ('prostate_history', models.NullBooleanField()),
                ('trouble_urinating', models.NullBooleanField()),
                ('suspicious_nodule', models.NullBooleanField()),
                ('notes', models.CharField(max_length=300)),
            ],
        ),
    ]
