# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do paciente')),
                ('mother_name', models.CharField(max_length=100, verbose_name='Nome da mãe')),
                ('address', models.CharField(max_length=300, verbose_name='Endereço')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('birthdate', models.DateField(verbose_name='Data de nascimento')),
                ('prostate_history', models.NullBooleanField(verbose_name='Tem alguém na família com problemas na próstata')),
                ('trouble_urinating', models.NullBooleanField(verbose_name='Problemas para urinar?')),
                ('suspicious_nodule', models.NullBooleanField(verbose_name='Possui nódulo suspeito?')),
                ('notes', models.CharField(max_length=300, null=True, verbose_name='Observações')),
                ('has_referral', models.NullBooleanField()),
                ('referral_character', models.CharField(choices=[('0', 'ELETIVO'), ('1', 'URGÊNCIA')], max_length=100, verbose_name='Caráter')),
                ('referral_place', models.CharField(choices=[('0', 'Clínica da família'), ('1', 'Policlínica Piquet Carneiro'), ('2', 'Outro')], max_length=100, verbose_name='Local de encaminhamento')),
                ('other_referral_place', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
