# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do paciente'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='notes',
            field=models.CharField(max_length=300, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prostate_history',
            field=models.NullBooleanField(verbose_name='Tem alguém na família com problemas na próstata'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='suspicious_nodule',
            field=models.NullBooleanField(verbose_name='Possui nódulo suspeito?'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='trouble_urinating',
            field=models.NullBooleanField(verbose_name='Problemas para urinar?'),
        ),
    ]
