# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_psa_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da mãe'),
        ),
    ]
